on: pull_request_target

name: Auto Merge Dependabot PRs

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    # only run for dependabot PRs
    if: ${{ github.actor == 'dependabot[bot]' }}

    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

    steps:
      - name: auto approve & merge
        run: |
          gh pr review --approve "$PR_URL"
          gh pr comment -b "@dependabot squash and merge" "$PR_URL"
